Prep2Plate/Models/UserPreference.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Prep2Plate.Models
{
    public class UserPreference
    {
        [Key]
        public string UserName { get; set; }
        public string Preferences { get; set; }

    }
}

Prep2Plate/Controllers/UserPreferencesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Prep2Plate.Models;

namespace Prep2Plate.Controllers
{
    public class UserPreferencesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: UserPreferences
        public ActionResult Index()
        {
            return View(db.UserPreference.ToList());
        }

        // GET: UserPreferences/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserPreference userPreference = db.UserPreference.Find(id);
            if (userPreference == null)
            {
                return HttpNotFound();
            }
            return View(userPreference);
        }

        // GET: UserPreferences/Create
        public ActionResult Create()
        {
            UserPreference db = new UserPreference();


            return View();
        }

        // POST: UserPreferences/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UserName,Preferences")] UserPreference userPreference)
        {
            if (ModelState.IsValid)
            {
                db.UserPreference.Add(userPreference);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(userPreference);
        }

        // GET: UserPreferences/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserPreference userPreference = db.UserPreference.Find(id);
            if (userPreference == null)
            {
                return HttpNotFound();
            }
            return View(userPreference);
        }

        // POST: UserPreferences/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UserName,Preferences")] UserPreference userPreference)
        {
            if (ModelState.IsValid)
            {
                db.Entry(userPreference).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(userPreference);
        }

        // GET: UserPreferences/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserPreference userPreference = db.UserPreference.Find(id);
            if (userPreference == null)
            {
                return HttpNotFound();
            }
            return View(userPreference);
        }

        // POST: UserPreferences/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            UserPreference userPreference = db.UserPreference.Find(id);
            db.UserPreference.Remove(userPreference);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Prep2Plate/Views/UserPreferences/Create.cshtml
@model Prep2Plate.Models.UserPreference

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UserPreference</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Preferences, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Preferences, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Preferences, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Prep2Plate/Views/UserPreferences/Details.cshtml
@model Prep2Plate.Models.UserPreference

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>UserPreference</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Preferences)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Preferences)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.UserName }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Prep2Plate/Views/UserPreferences/Index.cshtml
@model IEnumerable<Prep2Plate.Models.UserPreference>

@{
    ViewBag.Title = "Index";
}

<h2>Dietary Preferences</h2>


@using (Html.BeginForm("Index", "UserPreferences", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    <div class="text-center">
        <div class="form-group">
            @*@Html.LabelFor(p => p.Diet)*@
            <label for="Diet">Please select your dietary preferences:</label>
        </div>

        <button class="btn btn-primary" data-toggle="button" aria-pressed="true" autocomplete="off">Vegetarian</button>

        <button class="btn btn-primary" data-toggle="button" aria-pressed="false" autocomplete="off">Pescetarian</button>

        <button class="btn btn-primary" data-toggle="button" aria-pressed="false" autocomplete="off">Vegan</button>

        <button class="btn btn-primary" data-toggle="button" aria-pressed="false" autocomplete="off">Kosher</button>

        <button class="btn btn-primary" data-toggle="button" aria-pressed="false" autocomplete="off">Gluten-Free</button>

        <button class="btn btn-primary" data-toggle="button" aria-pressed="false" autocomplete="off">Dairy Free</button>

        <br />
        <br />
        @*<div class="btn btn-primary" data-toggle="button" aria-pressed="false" autocomplete="off">
            <button class="btn btn-primary">Allergies:</button>
            @Html.TextBoxFor(p => p.Diet)*@
        @*</div>
            <br />
            <br />*@


        @*<div class="form-group">
                <label for="PreferredShoppingDay">What are your preferred shopping days?</label>
            </div>
            <button class="btn btn-primary" data-toggle="button" aria-pressed="false" autocomplete="off">Sunday</button>

            <button class="btn btn-primary" data-toggle="button" aria-pressed="false" autocomplete="off">Monday</button>

            <button class="btn btn-primary" data-toggle="button" aria-pressed="false" autocomplete="off">Tuesday</button>

            <button class="btn btn-primary" data-toggle="button" aria-pressed="false" autocomplete="off">Wednesday</button>

            <button class="btn btn-primary" data-toggle="button" aria-pressed="false" autocomplete="off">Thursday</button>

            <button class="btn btn-primary" data-toggle="button" aria-pressed="false" autocomplete="off">Friday</button>

            <button class="btn btn-primary" data-toggle="button" aria-pressed="false" autocomplete="off">Saturday</button>

            <br />
            <br />

            <div class="form-group">
                <label for="PreferredCookingDay">What are your preferred cooking days?</label>
            </div>

            <button class="btn btn-primary" data-toggle="button" aria-pressed="false" autocomplete="off">Sunday</button>

            <button class="btn btn-primary" data-toggle="button" aria-pressed="false" autocomplete="off">Monday</button>

            <button class="btn btn-primary" data-toggle="button" aria-pressed="false" autocomplete="off">Tuesday</button>

            <button class="btn btn-primary" data-toggle="button" aria-pressed="false" autocomplete="off">Wednesday</button>

            <button class="btn btn-primary" data-toggle="button" aria-pressed="false" autocomplete="off">Thursday</button>

            <button class="btn btn-primary" data-toggle="button" aria-pressed="false" autocomplete="off">Friday</button>

            <button class="btn btn-primary" data-toggle="button" aria-pressed="false" autocomplete="off">Saturday</button>

            <br />
            <br />*@

        @*<div class="form-group">*@
        @*@Html.LabelFor(p => p.MealsToPrep)*@
        @*<label for="MealsToPrep">Which meals are you prepping for?</label>*@
        @*</div>*@

        @*<button class="btn btn-primary" data-toggle="button" aria-pressed="false" autocomplete="off">Breakfast</button>

            <button class="btn btn-primary" data-toggle="button" aria-pressed="false" autocomplete="off">Lunch</button>

            <button class="btn btn-primary" data-toggle="button" aria-pressed="false" autocomplete="off">Dinner</button>*@

        @*<br />
            <br />
            <br />*@
        <div>
            <button href="https://localhost:44340/RecipesSearch" class="btn btn-primary" type="submit"><b><em>PREP!</em></b></button>
        </div>
    </div>
}

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Preferences)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Preferences)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.UserName }) |
            @Html.ActionLink("Details", "Details", new { id=item.UserName }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.UserName })
        </td>
    </tr>
}

</table>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}