Prep2Plate/Models/UserRecipe.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Prep2Plate.Models
{
    public class UserRecipe
    {
        [Key, Column(Order = 0)]
        public string RecipeId { get; set; }

        public string ImageUrl { get; set; }
        public string RecipeName { get; set; }
        public string Ingredients { get; set; }
        public string RecipeSourceUrl { get; set; }

        [Key, Column(Order = 1)]
        public string UserName { get; set; }
    }
}

Prep2Plate/Controllers/RecipeSearchController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json.Linq;
using Prep2Plate.Context;
using Prep2Plate.Models;

namespace Prep2Plate.Controllers
{
    [Authorize]
    public class RecipesSearchController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();        
        ////Hosted web API REST Service base url  
        private string AppId = "bf728886";
        private string AppKey = "a1608c3e5cc021f4354aa6755f42c294";
        private string Baseurl = "http://api.yummly.com/v1/";

        // Function called before the Page is loaded
        public ActionResult Index(int? id)
        {
            if (id.HasValue)
            {
            }
            else
            {
                ClearDatabase();
            }
            return View(db.RecipeSearchResults.ToList());
        }

        public ActionResult OnSearchRecipe(string searchRecipe)
        {
            try
            {
                ClearDatabase();
                string _requestUrl = "api/recipes?_app_id=" + AppId + "&_app_key=" + AppKey +
                                     "&requirePictures=true&q=" + searchRecipe;
                string httpResponse = CallYumlyApi(_requestUrl);
                ParseSearchResultsResponseAndStoreInDb(httpResponse);
                return RedirectToAction("Index", new {id = -1});
            }
            catch (Exception e)
            {
                TempData["ErrorMessage"] = GetErrorMessage(e);
                return RedirectToAction("Error");
            }
        }

        private string GetErrorMessage(Exception e)
        {
            string errorMessage = e.Message;
            while (e.InnerException != null)
            {
                e = e.InnerException;
                errorMessage = errorMessage + "\n" + e.Message;
            }
            return errorMessage;
        }

        private string CallYumlyApi(string requestUrl)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(Baseurl);
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                //Sending request to find web api REST service resource GetAllEmployees using HttpClient  
                var htttpResponse = client.GetAsync(requestUrl);
                htttpResponse.Wait();
                var htttpResult = htttpResponse.Result;
                return htttpResult.Content.ReadAsStringAsync().Result;
            }
        }

        private void ParseSearchResultsResponseAndStoreInDb(string httpResponse)
        {
            JObject jObect = JObject.Parse(httpResponse);
            IList<JToken> jTokenList = jObect["matches"].Children().ToList();
                
            // serialize JSON results into .NET objects
            foreach(JToken jToken in jTokenList)
            {
                RecipeSearchResult recipeSearchResult = new RecipeSearchResult
                {
                    Id = jToken["id"].ToString(),
                    RecipeName = jToken["recipeName"].ToString(),
                    ImageUrl = jToken["imageUrlsBySize"]["90"].ToString()
                };
                db.RecipeSearchResults.Add(recipeSearchResult);
            }
            db.SaveChanges();
        }

        public void ParseGetResultsResponseAndUpdateInDb(string httpResponse, RecipeSearchResult recipeSearchResult)
        {
            JObject jObect = JObject.Parse(httpResponse);
            recipeSearchResult.Ingredients = jObect["ingredientLines"].ToString();
            recipeSearchResult.RecipeSourceUrl = jObect["source"]["sourceRecipeUrl"].ToString();
            db.SaveChanges();
        }

        public ActionResult Details(string id)
        {
            try
            {
                RecipeSearchResult recipeSearchResult = db.RecipeSearchResults.Find(id);
                if (recipeSearchResult.Ingredients == null)
                {
                    string _requestUrl =
                        "api/recipe/" + recipeSearchResult.Id + "?_app_id=" + AppId + "&_app_key=" + AppKey;
                    string httpResponse = CallYumlyApi(_requestUrl);
                    ParseGetResultsResponseAndUpdateInDb(httpResponse, recipeSearchResult);
                }
                return View(recipeSearchResult);
            }
            catch (Exception e)
            {
                TempData["ErrorMessage"] = GetErrorMessage(e);
                return RedirectToAction("Error");
            }
        }

        public ActionResult Error()
        {
            return View();
        }

        private void ClearDatabase()
        {
            foreach (var recipeSearchResult in db.RecipeSearchResults)
            {
                db.RecipeSearchResults.Remove(recipeSearchResult);
            }
            db.SaveChanges();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult SaveRecipe(String id)
        {
            RecipeSearchResult result = db.RecipeSearchResults.Find(id);
            if (result != null)
            {
                UserRecipe userRecipe = db.UserRecipes.Find(result.Id, User.Identity.Name);
                if (userRecipe == null)
                {
                    userRecipe = new UserRecipe();
                    userRecipe.RecipeId = result.Id;
                    userRecipe.RecipeName = result.RecipeName;
                    userRecipe.ImageUrl = result.ImageUrl;
                    userRecipe.RecipeSourceUrl = result.RecipeSourceUrl;
                    userRecipe.Ingredients = result.Ingredients;

                    userRecipe.UserName = User.Identity.Name;

                    db.UserRecipes.Add(userRecipe);
                    db.SaveChanges();
                }
            }
            return RedirectToAction("Index", "UserRecipes");
        }
    }
}

Prep2Plate/Controllers/UserRecipesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Prep2Plate.Models;

namespace Prep2Plate.Controllers
{
    [Authorize]
    public class UserRecipesController : Controller
    {
        // Creating instance of the db context class to access the model.
            private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index()
        {
            return View(db.UserRecipes.Where(userRecipe => userRecipe.UserName.Equals(User.Identity.Name)).ToList());
        }

        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserRecipe userRecipe = db.UserRecipes.Find(id, User.Identity.Name);
            if (userRecipe == null)
            { 
                return HttpNotFound();
            }

            return View(userRecipe);
        }

        public ActionResult AddToCalendar(string id)
        {
            return RedirectToAction("Index", "RecipeCalendar", new { id = id });
        }

        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserRecipe userRecipe = db.UserRecipes.Find(id, User.Identity.Name);
            if (userRecipe == null)
            {
                return HttpNotFound();
            }
           
            return View(userRecipe);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            UserRecipe userRecipe = db.UserRecipes.Find(id, User.Identity.Name);
            db.UserRecipes.Remove(userRecipe);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Prep2Plate/Views/UserRecipes/Delete.cshtml
@model Prep2Plate.Models.UserRecipe

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this Recipe?</h3>
<div>
    <h4>@Html.DisplayFor(model => model.RecipeName)</h4>
    <hr />

    <p /><p />
    <img src="@Url.Content(Model.ImageUrl)" />

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Prep2Plate/Views/UserRecipes/Details.cshtml
@model Prep2Plate.Models.UserRecipe

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>UserRecipe</h4>
    <hr />    
    <p>
        @Html.ActionLink("Back to List", "Index")
    </p>
    
    <p/><p/>
    <p><b> @Html.DisplayNameFor(model => model.RecipeName) </b></p>
    <p>@Html.DisplayFor(model => model.RecipeName)</p>

    <p /><p />
    <img src="@Url.Content(Model.ImageUrl)" />
   
    <p/><p/>
    <p><b> @Html.DisplayNameFor(model => model.Ingredients) </b></p>
    @{
        var items = Json.Decode(Model.Ingredients); 
    }
    <ul>
        @foreach (var item in items)
        {
            <li>@item.ToString()</li>
        }    
    </ul>
    <a href="@Model.RecipeSourceUrl" target="_blank"><b>Click Here For More Recipe Details</b></a>
    <br/><br/>

</div>

Prep2Plate/Views/UserRecipes/Index.cshtml
@using Prep2Plate.Controllers
@model IEnumerable<Prep2Plate.Models.UserRecipe>

@{
    ViewBag.Title = "Index";
}

<h2>My Recipe</h2>
<p>
    @Html.ActionLink("Back to Recipe Search", "Index","RecipesSearch", new { id = -1 }, null)
</p>

<table class="table">
    
    <tr>
        <th>Recipe Name</th>
        <th>Image</th>
        <th>Add to Calendar</th>
        <th>Delete</th>
    </tr>

    </tr>

    @foreach (var item in Model)
    {
       <tr>
           <td>
               <a href="@Url.Action("Details", "UserRecipes",new { id=item.RecipeId})">
                   @Html.DisplayFor(modelItem => item.RecipeName)
               </a>
           </td>
           <td>               
               <a href="@Url.Action("Details", "UserRecipes",new { id=item.RecipeId})">
                   <img src="@Url.Content(@item.ImageUrl)" />
               </a>
            </td>
           <td>
               @using (Html.BeginForm("AddToCalendar", "UserRecipes",new{id = item.RecipeName}))
               {
                   <input type="submit" value="Add to Calendar" id="btnAdd" />
               }
           </td>
            <td>
                @Html.ActionLink("Delete", "Delete", new { id=item.RecipeId})
            </td>
       </tr>
    }
</table>

<style>
    .table > tbody > tr > td {
        vertical-align: middle
    }
</style>