Prep2Plate/Controllers/RecipeCalendarController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Prep2Plate.Models;

namespace Prep2Plate.Controllers
{
    [Authorize]
    public class RecipeCalendarController : Controller
    {
        private static string _recipeName;
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index(string id)
        {
            if (id == null)
            {
                ViewData["clickable"] = false;
            }
            else
            {
                ViewData["clickable"] = true;
            }
            _recipeName = id;
            return View(db.RecipeCalendar.ToList());
        }


        public ActionResult SaveRecipeToCalendar(int dayOfWeek, int type)
        {
            RecipeCalendarData calendarData = new RecipeCalendarData();
            calendarData.UserName = User.Identity.Name;
            calendarData.DayOfTheWeek = dayOfWeek;
            calendarData.TypeOfMeal = type;
            calendarData.RecipeName = _recipeName;
            db.RecipeCalendar.AddOrUpdate(calendarData);
            db.SaveChanges();
            return RedirectToAction("Index", new {id = _recipeName});
        }

        public ActionResult RemoveRecipeFromCalendar(int dayOfWeek, int type)
        {
            RecipeCalendarData calendarData =  db.RecipeCalendar.Find(User.Identity.Name, dayOfWeek, type);
            db.RecipeCalendar.Remove(calendarData);
            db.SaveChanges();
            return RedirectToAction("Index", new { id = _recipeName });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Prep2Plate/Views/RecipeCalendar/Index.cshtml
@using System.Globalization
@model IEnumerable<Prep2Plate.Models.RecipeCalendarData>

@{
    ViewBag.Title = "Index";
}

<h2>My Calendar</h2>

<table class="table table-striped">
    <tr>
        <th></th>
        <th>BREAKFAST</th>
        <th>LUNCH</th>
        <th>DINNER</th>
    </tr>

    @{
        const int MAX_NUM_OF_DAYS = 7;
        const int MAX_NUM_OF_MEAL_TYPES = 3;
        CultureInfo cultureInfo = new System.Globalization.CultureInfo("en-US");
        string userName = User.Identity.Name;

        for (int i = 0; i < MAX_NUM_OF_DAYS; i++)
        {
            <tr>
                <td>@cultureInfo.DateTimeFormat.GetDayName((DayOfWeek)i)</td>

                @for (int j = 0; j < MAX_NUM_OF_MEAL_TYPES; j++)
                {
                    <td>
                        @if (@Model.FirstOrDefault(calendarData => calendarData.DayOfTheWeek.Equals(i) && 
                                                                    calendarData.TypeOfMeal.Equals(j) && 
                                                                    calendarData.UserName.Equals(userName)) == null)
                        {
                            if (ViewData["clickable"].Equals(true))
                            {
                                <a href="@Url.Action("SaveRecipeToCalendar", "RecipeCalendar", new {dayOfWeek = i, type = j})"> Add Here</a>
                            }
                            else
                            {
                                <p>-</p>
                            }
                        }
                        else
                        {
                            if (ViewData["clickable"].Equals(true))
                            {
                                <a href="@Url.Action("RemoveRecipeFromCalendar", "RecipeCalendar", new {dayOfWeek = i, type = j})">
                                     @Model.FirstOrDefault(calendarData => calendarData.DayOfTheWeek.Equals(i) && 
                                                                            calendarData.TypeOfMeal.Equals(j) && 
                                                                            calendarData.UserName.Equals(userName)).RecipeName
                                </a>
                            }
                            else
                            {
                                <p>@Model.FirstOrDefault(calendarData => calendarData.DayOfTheWeek.Equals(i) && 
                                                                        calendarData.TypeOfMeal.Equals(j) && 
                                                                        calendarData.UserName.Equals(userName)).RecipeName
                                </p>
                            }
                        }
                    </td>
                }

            </tr>        
        }
    }
</table>
<input type="button" onclick="javascript: window.print();" value="Print Your Calendar" />
<style>
    a[href]:after {
        content: none !important;
    }
</style>